<x-customer-layout :customer-view="$customerView"><main>
<a class="back-link" href="{{ $customerView ? route('platform.customer-view.bills') : route('customer.bills', $organization->id) }}">← Bill register</a>
<div class="heading"><div><div class="eyebrow">{{ $bill->location }} · {{ \Carbon\CarbonImmutable::parse($bill->period)->format('M Y') }}</div><h1>{{ $bill->reference }}</h1><p>{{ $bill->supplier }} · {{ $bill->commodity }}</p></div><span class="status-badge {{ $bill->display_status }}">{{ ['review' => 'Needs review', 'verified' => 'Verified', 'missing' => 'Missing statement', 'awaiting' => 'Awaiting statement'][$bill->display_status] ?? 'Unknown status' }}</span></div>
@include('partials.auth-feedback')
<div class="bill-detail-grid"><div>
<section class="panel"><div class="panel-heading"><h2>Statement summary</h2></div><dl class="statement-summary"><div><dt>Current charges</dt><dd>{{ $bill->charges_cents === null ? 'Not received' : $bill->currency.' '.number_format($bill->charges_cents / 100, 2) }}</dd></div><div><dt>Expected by</dt><dd>{{ $bill->expectation_source === 'intake' ? 'Not scheduled — received through intake' : $bill->expected_by }}</dd></div><div><dt>Received on</dt><dd>{{ $bill->received_on ?? 'Not received' }}</dd></div><div><dt>Due on</dt><dd>{{ $bill->due_on ?? 'Not available' }}</dd></div>@if($bill->invoice_number)<div><dt>Invoice number / issued</dt><dd>{{ $bill->invoice_number }} · {{ $bill->issued_on }}</dd></div><div><dt>Service period</dt><dd>{{ $bill->service_start }} — {{ $bill->service_end }}</dd></div><div><dt>Balance forward</dt><dd>{{ $bill->currency }} {{ number_format($bill->balance_forward_cents / 100, 2) }}</dd></div><div><dt>Amount due on statement</dt><dd>{{ $bill->currency }} {{ number_format($bill->amount_due_cents / 100, 2) }}</dd></div><div><dt>Usage</dt><dd>{{ number_format($bill->usage_kwh, 3) }} kWh</dd></div>@endif</dl></section>
<section class="panel"><div class="panel-heading"><h2>{{ $bill->statement_id ? 'Recorded finding' : 'Collection status' }}</h2></div><div class="detail-body"><p class="finding-copy">{{ $bill->evidence ?? 'No statement has been received for this expected bill.' }}</p></div></section>
<section class="panel document-placeholder">@if($document)<h2>Source statement</h2><p>{{ $document->filename }}</p><a class="inspect" href="{{ $customerView ? route('platform.customer-view.document', $bill->id) : route('customer.bills.document', [$organization->id, $bill->id]) }}">Download PDF</a>@else<h2>No source document available</h2>@endif<p>Verification records a review decision; it does not authorize or confirm payment. Amount due is historical, as printed on this statement.</p></section>
<section class="panel"><div class="panel-heading"><h2>Review history</h2></div>
@forelse($history as $event)<article class="review-event"><div><strong>{{ $event->to_status === 'verified' ? 'Verified' : 'Reopened' }} · {{ $event->actor_name }}</strong><time>{{ \Carbon\CarbonImmutable::parse($event->created_at)->utc()->format('M j, Y H:i') }} UTC</time></div><p>{{ $event->note }}</p></article>@empty<div class="empty">No review decisions recorded.</div>@endforelse
<div class="pagination">{{ $history->links() }}</div></section>
</div><aside class="panel review-form">
@if($canReview && in_array($bill->status, ['review', 'verified']))
<h2>{{ $bill->status === 'review' ? 'Review statement' : 'Reopen statement' }}</h2><p>Record your reasoning. The original finding remains visible in the statement record.</p>
<form method="POST" action="{{ route('customer.bills.review', [$organization->id, $bill->id]) }}">@csrf
<input type="hidden" name="version" value="{{ old('version', $bill->review_version) }}"><input type="hidden" name="decision" value="{{ $bill->status === 'review' ? 'verify' : 'reopen' }}">
<label for="review-note">{{ $bill->status === 'review' ? 'Resolution note' : 'Reason to reopen' }}</label><textarea id="review-note" name="note" required minlength="10" maxlength="2000" rows="6">{{ old('note') }}</textarea><small>10–2,000 characters. Your name and the time are recorded.</small><button class="primary-button">{{ $bill->status === 'review' ? 'Save as verified' : 'Reopen review' }}</button></form>
@elseif(!$bill->statement_id)<h2>Awaiting a statement</h2><p>There is no received statement to review. Charges remain unknown until intake.</p>
@else<h2>Read-only access</h2><p>{{ $customerView ? 'Review actions are unavailable while viewing as a customer.' : 'Only reviewers with access to this property can change its review status.' }}</p>@endif
</aside></div></main></x-customer-layout>
