<x-customer-layout :customer-view="$customerView"><main>
<a class="back-link" href="{{ $customerView ? route('platform.customer-view.bills') : route('customer.bills', $organization->id) }}">← Bill register</a>
<div class="heading"><div><div class="eyebrow">{{ $bill->location }} · {{ \Carbon\CarbonImmutable::parse($bill->period)->format('M Y') }}</div><h1>{{ $bill->reference }}</h1><p>{{ $bill->supplier }} · {{ $bill->commodity }}</p></div><span class="status-badge {{ $bill->display_status }}">{{ ['review' => 'Needs review', 'verified' => 'Verified', 'missing' => 'Missing statement', 'awaiting' => 'Awaiting statement', 'superseded' => 'Superseded version'][$bill->display_status] ?? 'Unknown status' }}</span></div>
@include('partials.auth-feedback')
@if($historical)<div class="revision-note"><strong>Historical version {{ $selectedRevision }}</strong><p>This version has been replaced and is excluded from current totals. Review history below identifies the version each decision applied to.</p><a class="inspect" href="{{ $customerView ? route('platform.customer-view.bill', $bill->id) : route('customer.bills.show', [$organization->id, $bill->id]) }}">View current version</a></div>@endif
<div class="bill-detail-grid"><div>
<section class="panel"><div class="panel-heading"><h2>Statement summary @if($bill->statement_id) · Version {{ $selectedRevision }} @endif</h2></div><dl class="statement-summary"><div><dt>Current charges</dt><dd>{{ $bill->charges_cents === null ? 'Not received' : $bill->currency.' '.number_format($bill->charges_cents / 100, 2) }}</dd></div><div><dt>Expected by</dt><dd>{{ $bill->expectation_source === 'intake' ? 'Not scheduled — received through intake' : $bill->expected_by }}</dd></div><div><dt>Received on</dt><dd>{{ $bill->received_on ?? 'Not received' }}</dd></div><div><dt>Due on</dt><dd>{{ $bill->due_on ?? 'Not available' }}</dd></div>@if($bill->invoice_number)<div><dt>Invoice number / issued</dt><dd>{{ $bill->invoice_number }} · {{ $bill->issued_on }}</dd></div><div><dt>Service period</dt><dd>{{ $bill->service_start }} — {{ $bill->service_end }}</dd></div><div><dt>Balance forward</dt><dd>{{ $bill->currency }} {{ number_format($bill->balance_forward_cents / 100, 2) }}</dd></div><div><dt>Amount due on statement</dt><dd>{{ $bill->currency }} {{ number_format($bill->amount_due_cents / 100, 2) }}</dd></div><div><dt>Usage</dt><dd>{{ number_format($bill->usage_kwh, 3) }} kWh</dd></div>@endif</dl></section>
<section class="panel"><div class="panel-heading"><h2>{{ $bill->statement_id ? 'Recorded finding' : 'Collection status' }}</h2></div><div class="detail-body"><p class="finding-copy">{{ $bill->evidence ?? 'No statement has been received for this expected bill.' }}</p></div></section>
<section class="panel document-placeholder">@if($document)<h2>Source statement</h2><p>{{ $document->filename }}</p><a class="inspect" href="{{ $customerView ? route('platform.customer-view.document', ['bill' => $bill->id, 'revision' => $selectedRevision]) : route('customer.bills.document', ['organization' => $organization->id, 'bill' => $bill->id, 'revision' => $selectedRevision]) }}">Download PDF</a>@else<h2>No source document available</h2>@endif<p>Verification records a review decision; it does not authorize or confirm payment. Amount due is historical, as printed on this statement.</p></section>
<section class="panel"><div class="panel-heading"><h2>Detailed current charges</h2></div>
@if($lineItems->isNotEmpty())<div class="charge-table"><table><thead><tr><th>Charge / source</th><th>Quantity</th><th>Rate</th><th class="charge-amount">Amount</th></tr></thead><tbody>
@foreach($lineItems as $item)<tr><td>{{ $item->description }}<small>{{ \App\Billing\StatementCharges::CATEGORIES[$item->category] ?? $item->category }} @if($item->source_reference) · {{ $item->source_reference }} @endif</small></td><td>{{ $item->quantity ?? '—' }} {{ $item->unit }}</td><td>{{ $item->rate ?? '—' }} {{ $item->rate_unit }}</td><td class="charge-amount">{{ $bill->currency }} {{ number_format($item->amount_cents / 100, 2) }}</td></tr>@endforeach
</tbody><tfoot><tr><th colspan="3">Current charges · excludes prior balance</th><th class="charge-amount">{{ $bill->currency }} {{ number_format($bill->charges_cents / 100, 2) }}</th></tr></tfoot></table></div>
@else<div class="empty">No detailed charges recorded for this version. Summary values remain available.</div>@endif</section>
@if($revisions->isNotEmpty())<section class="panel"><div class="panel-heading"><h2>Statement versions</h2></div><ul class="revision-list">
@foreach($revisions as $revision)<li><a class="inspect" href="{{ $customerView ? route('platform.customer-view.bill', ['bill' => $bill->id, 'revision' => $revision->number]) : route('customer.bills.show', ['organization' => $organization->id, 'bill' => $bill->id, 'revision' => $revision->number]) }}" @if($revision->number === $selectedRevision) aria-current="page" @endif>Version {{ $revision->number }} · {{ $revision->number === $bill->revision_number ? 'Current' : 'Superseded' }}</a><p>{{ $revision->reason }}</p><small>{{ $revision->actor_name ?? 'System record' }} · {{ \Carbon\CarbonImmutable::parse($revision->created_at)->utc()->format('M j, Y H:i') }} UTC</small></li>@endforeach
</ul></section>@endif
<section class="panel"><div class="panel-heading"><h2>Review history</h2></div>
@forelse($history as $event)<article class="review-event"><div><strong>{{ $event->to_status === 'verified' ? 'Verified' : 'Reopened' }} · {{ $event->actor_name }} · Version {{ $event->revision_number }}</strong><time>{{ \Carbon\CarbonImmutable::parse($event->created_at)->utc()->format('M j, Y H:i') }} UTC</time></div><p>{{ $event->note }}</p></article>@empty<div class="empty">No review decisions recorded.</div>@endforelse
<div class="pagination">{{ $history->links() }}</div></section>
</div><aside class="panel review-form">
@if($canReview && in_array($bill->status, ['review', 'verified']))
<a class="inspect" href="{{ route('customer.bills.correct', [$organization->id, $bill->id]) }}">Correct statement</a>
<h2>{{ $bill->status === 'review' ? 'Review statement' : 'Reopen statement' }}</h2><p>Record your reasoning. The original finding remains visible in the statement record.</p>
<form method="POST" action="{{ route('customer.bills.review', [$organization->id, $bill->id]) }}">@csrf
<input type="hidden" name="version" value="{{ old('version', $bill->review_version) }}"><input type="hidden" name="decision" value="{{ $bill->status === 'review' ? 'verify' : 'reopen' }}">
<label for="review-note">{{ $bill->status === 'review' ? 'Resolution note' : 'Reason to reopen' }}</label><textarea id="review-note" name="note" required minlength="10" maxlength="2000" rows="6">{{ old('note') }}</textarea><small>10–2,000 characters. Your name and the time are recorded.</small><button class="primary-button">{{ $bill->status === 'review' ? 'Save as verified' : 'Reopen review' }}</button></form>
@elseif(!$bill->statement_id)<h2>Awaiting a statement</h2><p>There is no received statement to review. Charges remain unknown until intake.</p>
@else<h2>Read-only access</h2><p>{{ $historical ? 'Historical versions cannot be edited or reviewed. Open the current version to make a correction.' : ($customerView ? 'Review actions are unavailable while viewing as a customer.' : 'Only reviewers with access to this property can change its review status.') }}</p>@endif
</aside></div></main></x-customer-layout>
