<x-customer-layout><main class="statement-intake">
<a class="back-link" href="{{ route('customer.locations.show', [$organization->id, $account->location_id]) }}">← Utility accounts</a>
<div class="eyebrow">BILLING EXPECTATIONS</div><h1>{{ $account->reference }}</h1><p>{{ $account->supplier }} · {{ $account->commodity }}. A schedule describes when a bill should arrive, not when it must be paid.</p>
@include('partials.auth-feedback')
<div class="review-notice">This reporting month: {{ !$current ? 'No schedule configured — coverage unknown.' : ($current->mode === 'monthly' ? 'Monthly billing expected.' : 'No bill expected under the configured schedule.') }}</div>
@if($organization->owner_user_id === auth()->id())
<form class="auth-form" method="POST" action="{{ route('customer.accounts.schedule.store', [$organization->id, $account->id]) }}">@csrf
<input type="hidden" name="version" value="{{ old('version', $version) }}">
<h2>Set expectations from a reporting month</h2><p>Changes are recorded with your name and reason. Earlier months keep their earlier schedule. Changing a past month recalculates its expectations but never removes its statements.</p>
<div class="intake-fields"><div><label for="effective-month">Effective reporting month (YYYY-MM-01)</label><input id="effective-month" name="effective_month" value="{{ old('effective_month', today()->startOfMonth()->toDateString()) }}" required pattern="[0-9]{4}-[0-9]{2}-01"></div>
<div><label for="schedule-mode">Billing expectation</label><select id="schedule-mode" name="mode"><option value="monthly" @selected(old('mode', $current?->mode) !== 'not_expected')>Monthly bill expected</option><option value="not_expected" @selected(old('mode', $current?->mode) === 'not_expected')>No bill expected (closed / paused)</option></select></div>
<div><label for="receipt-day">Expected receipt day</label><input id="receipt-day" type="number" name="receipt_day" min="1" max="31" value="{{ old('receipt_day', $current?->receipt_day ?? 15) }}"><small>Days beyond the end of a short month use that month's final day.</small></div>
<div><label for="month-offset">Receipt month</label><select id="month-offset" name="month_offset"><option value="0" @selected(old('month_offset', $current?->month_offset) == 0)>Same as reporting month</option><option value="1" @selected(old('month_offset', $current?->month_offset) == 1)>Following reporting month</option></select></div>
<div><label for="grace-days">Grace period (days)</label><input id="grace-days" type="number" name="grace_days" min="0" max="30" value="{{ old('grace_days', $current?->grace_days ?? 5) }}"><small>Missing starts the day after receipt day + grace. Dates use UTC.</small></div></div>
<label for="schedule-reason">Reason / source of this schedule</label><textarea id="schedule-reason" name="reason" required minlength="10" maxlength="2000" rows="3">{{ old('reason') }}</textarea><small>Receipt settings are ignored for No bill expected. Irregular/custom cycles and separate supplier streams are not supported yet.</small><button class="primary-button">Save billing schedule</button></form>
@else<p>Only the account owner can change billing expectations.</p>@endif
<section class="panel"><div class="panel-heading"><h2>Schedule history</h2></div><ul class="revision-list">@forelse($history as $event)<li><strong>From {{ $event->effective_month }} · {{ $event->mode === 'monthly' ? 'Monthly' : 'No bill expected' }}</strong>@if($event->mode === 'monthly')<p>Receipt day {{ $event->receipt_day }}, {{ $event->month_offset ? 'following' : 'same' }} month · {{ $event->grace_days }} grace days</p>@endif<p>{{ $event->reason }}</p><small>{{ $event->actor_name }} · {{ $event->created_at }} UTC</small></li>@empty<li>No schedule configured. Receiving a statement does not create a recurring billing expectation.</li>@endforelse</ul></section>
</main></x-customer-layout>
