<x-customer-layout :customer-view="$customerView ?? null"><main><a class="back-link" href="{{ isset($customerView) ? route('platform.customers.show', $organization->id) : route('customer.home') }}">← {{ isset($customerView) ? 'Customer details' : 'My accounts' }}</a><div class="heading"><div><div class="eyebrow">CUSTOMER WORKSPACE</div><h1>{{ $organization->name }}</h1><p>Your account's utility-bill workspace.</p></div></div>
<p><a class="inspect" href="{{ isset($customerView) ? route('platform.customer-view.exceptions') : route('customer.exceptions', $organization->id) }}">Investigations &amp; follow-ups →</a></p>
@include('partials.auth-feedback')
@if($organization->is_test_account)<div class="review-notice">Test account · Private development data
@if($organization->legal_name)<br>{{ $organization->legal_name }}@endif</div>@endif
<p class="team-entry"><a class="inspect" href="{{ isset($customerView) ? route('platform.customer-view.bills') : route('customer.bills', $organization->id) }}">Browse bills →</a></p>
@if($organization->owner_user_id === ($viewUserId ?? auth()->id()))<p class="team-entry"><a class="inspect" href="{{ isset($customerView) ? route('platform.customer-view.team') : route('team.index', $organization->id) }}">Manage team & invitations →</a></p>@endif
<section class="metrics customer-metrics"><div class="metric"><span>Accessible locations</span><strong>{{ $locations->count() }}</strong></div><div class="metric"><span>Utility accounts</span><strong>{{ $accountCount }}</strong></div><div class="metric"><span>Received statements</span><strong>{{ $statementCount }}</strong></div></section>
@php
$billList = isset($customerView) ? route('platform.customer-view.bills') : route('customer.bills', $organization->id);
@endphp
<form class="toolbar bill-filters" method="GET"><label>Reporting month<input name="period" value="{{ $period }}" required pattern="[0-9]{4}-[0-9]{2}-01" aria-label="Reporting month (YYYY-MM-01)"></label><button class="inspect">Show month</button><small>Expected receipt dates and grace periods use UTC.</small></form>
<section class="metrics customer-metrics">
<a class="metric" href="{{ $billList.'?'.http_build_query(['status' => 'missing', 'period' => $period]) }}"><span>Missing after grace · selected month</span><strong>{{ $pendingCount ? '—' : $missingCount }}</strong><small>Open the collection queue →</small></a>
<a class="metric" href="{{ $billList.'?'.http_build_query(['status' => 'awaiting', 'period' => $period]) }}"><span>Awaiting receipt · selected month</span><strong>{{ $pendingCount ? '—' : $awaitingCount }}</strong><small>Still within the receipt window →</small></a>
<a class="metric" href="{{ $billList.'?status=review' }}"><span>Needs review · all months</span><strong>{{ $reviewCount }}</strong><small>Open the review queue →</small></a>
</section>
<section class="panel"><div class="panel-heading"><div><h2>Collection coverage · {{ \Carbon\CarbonImmutable::parse($period)->format('M Y') }}</h2><p>@if($scheduledCount && !$pendingCount){{ $expectedReceived }} of {{ $scheduledCount }} scheduled bills received.@elseif($pendingCount)Coverage pending refresh: {{ $pendingCount }} scheduled expectations have not been generated for this month.@else No monthly schedules apply. Completeness is unknown.@endif</p></div></div><div class="detail-body"><p>{{ $unknownCount }} accounts without a schedule · {{ $excludedCount }} explicitly not expected this month.</p><p>Latest recorded receipt: {{ $lastReceived ?? 'No statements received' }}. This is a receipt date, not proof of an active provider connection.</p><p>Configure schedules from a location's utility accounts. Unscheduled accounts are excluded from the scheduled-bill denominator.</p></div></section>
<section class="panel"><div class="panel-heading"><div><h2>Missing bills to collect</h2><p>Oldest five missing expectations across all months. No statement amount is assumed.</p></div></div>
@forelse($missingBills as $missingBill)<div class="property-row"><div><strong>{{ $missingBill->location }} · {{ $missingBill->reference }}</strong><small>{{ $missingBill->period }} · Expected {{ $missingBill->expected_by }} · Grace through {{ $missingBill->missing_after ?? $missingBill->expected_by }}</small></div><a class="inspect" href="{{ isset($customerView) ? route('platform.customer-view.bill', $missingBill->id) : route('customer.bills.show', [$organization->id, $missingBill->id]) }}">Inspect expectation →</a></div>@empty<div class="empty">No overdue expectations recorded for your accessible properties. Unconfigured schedules remain unknown.</div>@endforelse</section>
<section class="panel"><div class="panel-heading"><div><h2>Statements needing review</h2><p>Oldest five statements awaiting a review decision, across all months.</p></div></div>
@forelse($reviewBills as $reviewBill)<div class="property-row"><div><strong>{{ $reviewBill->location }} · {{ $reviewBill->reference }}</strong><small>{{ $reviewBill->supplier }} · {{ $reviewBill->period }} · {{ $reviewBill->currency }} {{ number_format($reviewBill->charges_cents / 100, 2) }} current charges</small></div><a class="inspect" href="{{ isset($customerView) ? route('platform.customer-view.bill', $reviewBill->id) : route('customer.bills.show', [$organization->id, $reviewBill->id]) }}">Inspect statement →</a></div>@empty<div class="empty">No statements need review for your accessible properties.</div>@endforelse
</section>
<section class="panel"><div class="panel-heading"><h2>Your locations</h2>@if(!isset($customerView) && $organization->owner_user_id === auth()->id())<a class="inspect" href="{{ route('customer.locations.create', $organization->id) }}">+ Add location</a>@endif</div>@forelse($locations as $location)<div class="property-row"><strong>{{ $location->name }}</strong>@unless(isset($customerView))<a class="inspect" href="{{ route('customer.locations.show', [$organization->id, $location->id]) }}">View utility accounts →</a>@endunless</div>@empty<div class="empty"><h3>Your workspace is ready.</h3><p>No locations are available yet. Account owners can add a location; teammates need property access assigned by the owner.</p></div>@endforelse</section></main></x-customer-layout>
