<div>
@include('partials.workspace-nav')
<main>
    <a class="back-link" href="{{ route('bills') }}">← Bill register</a>
    <div class="heading"><div><div class="eyebrow">SEPTEMBER 2026 · {{ $bill['property'] }}</div><h1>{{ $bill['account'] }}</h1><p>{{ $bill['vendor'] }} · {{ $bill['commodity'] }}</p></div><span class="status-badge {{ $bill['status'] }}">{{ ['review' => 'Needs review', 'missing' => 'Missing statement', 'verified' => 'Verified', 'awaiting' => 'Not yet expected'][$bill['status']] }}</span></div>
    @if($message)<div class="review-notice" role="status">{{ $message }} <a href="{{ route('dashboard') }}">View dashboard →</a></div>@endif
    <div class="bill-detail-grid">
        <div>
            <section class="panel"><div class="panel-heading"><h2>Statement summary</h2><span class="pill">Fictional record</span></div><dl class="statement-summary"><div><dt>Received charges · USD</dt><dd>{{ $bill['cents'] === null ? 'Unknown' : '$'.number_format($bill['cents'] / 100, 2) }}</dd></div><div><dt>Timing</dt><dd>{{ $bill['date'] }}</dd></div><div><dt>Sample assignment</dt><dd>{{ $bill['owner'] }}</dd></div><div><dt>Payment status</dt><dd>Unavailable</dd></div></dl></section>
            <section class="panel"><div class="panel-heading"><h2>{{ $bill['statement_id'] ? 'Recorded finding' : 'Collection status' }}</h2></div><div class="detail-body"><p class="finding-copy">{{ $bill['evidence'] }}</p><p class="demo-note">{{ $bill['statement_id'] ? 'The original finding stays visible after review. These findings were seeded, not generated by a validation engine.' : 'A statement must be received before charges or a review decision can be recorded. Collection and intake are not implemented yet.' }}</p></div></section>
            <section class="panel document-placeholder"><div class="eyebrow">SOURCE DOCUMENT</div><h2>{{ $bill['statement_id'] ? 'No source bill attached' : 'Statement not received' }}</h2><p>The figures above are fictional fixtures. A document preview and extraction checks will follow when sample bills are available.</p></section>
            <section class="panel"><div class="panel-heading"><div><h2>Demo review history</h2><p>Local demo operator · no authenticated reviewer identity</p></div></div>
                @forelse($history as $event)<article class="review-event"><div><strong>{{ $event->to_status === 'verified' ? 'Marked verified' : 'Reopened for review' }}</strong><time>{{ \Carbon\CarbonImmutable::parse($event->created_at)->utc()->format('M j, Y · H:i') }} UTC</time></div><p>{{ $event->note }}</p></article>@empty<div class="empty">No review decisions recorded.</div>@endforelse
            </section>
        </div>
        <aside>
            <section class="panel review-form"><div class="eyebrow">NEXT STEP</div>
            @if($bill['statement_id'])
                <h2>{{ $bill['status'] === 'review' ? 'Resolve this finding' : 'Review completed' }}</h2><p>{{ $bill['status'] === 'review' ? 'Explain why this fictional finding can be accepted. The statement will count as verified.' : 'Need another look? Explain the reason to return this statement to the review queue.' }}</p>
                <form wire:submit="decide('{{ $bill['status'] === 'review' ? 'verify' : 'reopen' }}')">
                    <label for="review-note">{{ $bill['status'] === 'review' ? 'Resolution note' : 'Reason to reopen' }}</label><textarea id="review-note" wire:model="note" rows="6" minlength="10" maxlength="2000" required aria-describedby="note-help @error('note') note-error @enderror"></textarea><small id="note-help">10–2,000 characters. Fictional information only.</small>
                    @error('note')<p class="field-error" id="note-error" role="alert">{{ $message }}</p>@enderror
                    @error('decision')<p class="field-error" role="alert">{{ $message }}</p>@enderror
                    <button class="primary-button" type="submit" wire:loading.attr="disabled" wire:target="decide">{{ $bill['status'] === 'review' ? 'Save as verified' : 'Reopen review' }}</button>
                    <span wire:loading.delay wire:target="decide" role="status">Saving…</span>
                </form>
            @else<h2>Locate the statement</h2><p>{{ $bill['status'] === 'missing' ? 'The expected receipt date has passed.' : 'The expected receipt date has not passed.' }} Check the supplier portal or collection history when those connections become available.</p>@endif
                <p class="demo-note">Local workflow exercise. This does not approve a payment or create an operational audit trail.</p>
            </section>
        </aside>
    </div>
</main>
</div>
